import java.util.HashSet;

/**
 * Created by sreedish.ps on 14/10/14.
 */
public class FindMissing {
    static String ib = "processed_hour_id\n" +
            "event_day_id\n" +
            "request_day_id\n" +
            "adv_account_inc_id\n" +
            "adv_origin_country_id\n" +
            "adv_business_segment_id\n" +
            "adgroup_inc_id\n" +
            "adgroup_objective_id\n" +
            "pricing_model_id\n" +
            "ad_inc_id\n" +
            "campaign_inc_id\n" +
            "ad_content_id\n" +
            "ad_format_id\n" +
            "served_country_id\n" +
            "country_carrier_id\n" +
            "handset_device_id\n" +
            "device_type_id\n" +
            "browser_id\n" +
            "operating_system_id\n" +
            "operating_system_version_id\n" +
            "manufacturer_id\n" +
            "served_slot_id\n" +
            "served_ad_format\n" +
            "request_ad_format\n" +
            "budget_tier_id\n" +
            "adgroup_selected_bid\n" +
            "cpc_impressions\n" +
            "cpm_impressions\n" +
            "billed_cpc_clicks\n" +
            "non_billable_cpc_clicks\n" +
            "non_billable_impressions\n" +
            "total_burn\n" +
            "agency_revenue\n" +
            "inmobi_revenue\n" +
            "nofund_revenue\n" +
            "withhold_taxes\n" +
            "creative_charges\n" +
            "io_discount\n" +
            "volume_discount\n" +
            "cpm_billed_beacons\n" +
            "data_enrichment_cost\n" +
            "terminated_clicks\n" +
            "fraud_clicks\n" +
            "total_clicks\n" +
            "accidental_clicks\n" +
            "matched_conversions\n" +
            "served_impressions\n" +
            "cpm_clicks\n" +
            "pub_account_inc_id\n" +
            "pub_origin_country_id\n" +
            "pub_business_segment_id\n" +
            "site_inc_id\n" +
            "site_content_id\n" +
            "site_platform_id\n" +
            "site_channel_id\n" +
            "site_slot_id\n" +
            "demand_source_type_id\n" +
            "is_expandable\n" +
            "is_interstitial\n" +
            "is_click_to_rich\n" +
            "integration_method\n" +
            "integration_family\n" +
            "integration_version\n" +
            "integration_origin\n" +
            "integration_direct\n" +
            "predicted_clicks\n" +
            "participated_bid\n" +
            "participated_impressions\n" +
            "pub_revenue\n" +
            "channel_earnings\n" +
            "operator_id\n" +
            "request_slot_id\n" +
            "rm_source_name\n" +
            "rm_event_context_name\n" +
            "rm_event_action_name\n" +
            "rm_event_action_lookup\n" +
            "rm_custom_event_name\n" +
            "rm_event_label\n" +
            "rm_event_category\n" +
            "rm_external_id\n" +
            "rm_sprout_id\n" +
            "rm_count\n" +
            "rm_value\n" +
            "supply_source_type_id\n" +
            "page_requests\n" +
            "valid_page_requests\n" +
            "total_ad_requests\n" +
            "valid_ad_requests\n" +
            "channel_id\n" +
            "dcp_ad_requests\n" +
            "dcp_total_ad_impressions\n" +
            "dcp_external_impression_count\n" +
            "dcp_external_click_count\n" +
            "dcp_external_rev\n" +
            "dcp_inmobi_external_rev\n" +
            "dcp_internal_split_click_count\n" +
            "dcp_internal_split_impression_count\n" +
            "dcp_internal_total_impressions\n" +
            "dcp_internal_total_clicks\n" +
            "dcp_external_req_count\n" +
            "dcp_internal_beacon_count\n" +
            "dcp_internal_total_beacon_count\n" +
            "dcp_total_beacon_count\n" +
            "dcp_cpc_beacon_count\n" +
            "dcp_cpm_beacon_count\n" +
            "dcp_cpc_impressions\n" +
            "dcp_cpm_impressions\n" +
            "dcp_total_clicks\n" +
            "dcp_fraud_clicks\n" +
            "dcp_billed_cpc_clicks\n" +
            "dcp_non_billable_cpc_clicks\n" +
            "dcp_non_billable_cpm_impressions\n" +
            "dcp_total_burn\n" +
            "dcp_pub_revenue\n" +
            "dcp_agency_revenue\n" +
            "dcp_fraud_beacons\n" +
            "dcp_page_impressions\n" +
            "dcp_page_requests\n" +
            "dcp_valid_page_requests\n" +
            "dcp_valid_ad_requests\n" +
            "event_hour_id\n" +
            "request_hour_id";
    static String yoda = "bl_adgrpid\n" +
            "bl_agencycpc\n" +
            "bl_cpc\n" +
            "bl_createdon\n" +
            "bl_data_seller_id\n" +
            "bl_imptype\n" +
            "bl_io_discount\n" +
            "bl_loggingtime\n" +
            "bl_nofund_burn\n" +
            "bl_nondiscounted_burn\n" +
            "bl_overbill_revenue\n" +
            "bl_pubcpc\n" +
            "bl_siteid\n" +
            "bl_volume_discount\n" +
            "cl_ccid\n" +
            "cl_conv_factor\n" +
            "cl_fraud\n" +
            "cl_fraud_clicks\n" +
            "cl_fraudset\n" +
            "cl_handset\n" +
            "cl_jc\n" +
            "cl_other_invalid_clicks\n" +
            "cl_overbill_cpc_clicks\n" +
            "cl_rq_ccid\n" +
            "cl_terminated_clicks\n" +
            "cl_unbilled_cpc_clicks\n" +
            "cl_x_real_ip\n" +
            "cp_user_frequency\n" +
            "cp_user_unique_count\n" +
            "dcp_adreq\n" +
            "dcp_mkcpcadserved\n" +
            "dcp_mkvldadreq\n" +
            "dcp_mkvldpgreq\n" +
            "dcp_pgimp\n" +
            "dcp_pgreq\n" +
            "dcp_total_click_count\n" +
            "dl_carrier_city_id\n" +
            "dl_carrier_region_id\n" +
            "dl_duplicate_count\n" +
            "dl_goal\n" +
            "dl_install_count\n" +
            "dl_joined_count\n" +
            "dl_matched_count\n" +
            "dl_source\n" +
            "dl_terminated\n" +
            "dl_time\n" +
            "dl_unjoined_count\n" +
            "impid\n" +
            "rm_end_millis\n" +
            "rm_expand_count\n" +
            "rm_media_auto_play_count\n" +
            "rm_media_end_count\n" +
            "rm_media_play_count\n" +
            "rm_media_q1_count\n" +
            "rm_media_q2_count\n" +
            "rm_media_q3_count\n" +
            "rm_media_start_count\n" +
            "rm_source\n" +
            "rm_sprout_id\n" +
            "rm_start_millis\n" +
            "rq_ad_formatter\n" +
            "rq_ad_logic\n" +
            "rq_adformat\n" +
            "rq_adgrpidbig\n" +
            "rq_adid\n" +
            "rq_adimp\n" +
            "rq_adreq\n" +
            "rq_advid\n" +
            "rq_asm_segment_id\n" +
            "rq_campgnidbig\n" +
            "rq_cat_distance\n" +
            "rq_category\n" +
            "rq_ccid\n" +
            "rq_ecpm_goalseek\n" +
            "rq_h_user_agent\n" +
            "rq_handsetid\n" +
            "rq_host\n" +
            "rq_market\n" +
            "rq_mkcpcadserved\n" +
            "rq_mkvldadreq\n" +
            "rq_mkvldpgreq\n" +
            "rq_nodeinfo\n" +
            "rq_overbill_cpm_adimp\n" +
            "rq_pgimp\n" +
            "rq_pgreq\n" +
            "rq_slot_served\n" +
            "rq_time\n" +
            "rq_unbilled_cpm_adimp\n" +
            "user_adimp\n" +
            "user_app_dist_unique_user_count\n" +
            "user_app_ret_adimp\n" +
            "user_app_ret_pgimp\n" +
            "user_app_ret_unique_user_count\n" +
            "user_app_ret_vldadreq\n" +
            "user_app_ret_vldpgreq\n" +
            "user_ci_ret_adimp\n" +
            "user_ci_ret_pgimp\n" +
            "user_ci_ret_unique_user_count\n" +
            "user_ci_ret_vldadreq\n" +
            "user_ci_ret_vldpgreq\n" +
            "user_custom_segment_id\n" +
            "user_custom_segment_id_segment_retargeting\n" +
            "user_enrich_ad_req\n" +
            "user_enrich_pg_imp\n" +
            "user_enrich_pg_req\n" +
            "user_enrich_total_burn\n" +
            "user_enrich_unique_user_count\n" +
            "user_enrich_valid_clicks\n" +
            "user_life_lifespan\n" +
            "user_life_unique_user_count\n" +
            "user_location_context\n" +
            "user_location_context_ad_req\n" +
            "user_location_context_pg_req\n" +
            "user_location_context_unique_user_count\n" +
            "user_mkvldadreq\n" +
            "user_mkvldpgreq\n" +
            "user_optout\n" +
            "user_pgimp\n" +
            "user_ret_adgrpid\n" +
            "user_ret_engagetype\n" +
            "user_ret_installappid\n" +
            "user_segment_retargeting_ad_req\n" +
            "user_segment_retargeting_unique_user_count\n" +
            "user_sig_adimp\n" +
            "user_sig_click_count\n" +
            "user_sig_download_conversions\n" +
            "user_sig_spend\n" +
            "user_sig_unique_user_count\n" +
            "user_site_visited_count\n" +
            "user_unique_count\n" ;
   static  String yodarename = "is_expandable\n" +
           "is_interstitial\n" +
           "adgroup_selected_bid\n" +
           "adgroup_site_preference\n" +
           "adgroup_status\n" +
           "served_ad_impresisons\n" +
           "ad_inc_id\n" +
           "total_ad_requests\n" +
           "adgroup_inc_id\n" +
           "adv_account_guid\n" +
           "adv_business_segment\n" +
           "app_ret_ad_requests\n" +
           "cpm_billed_beacons\n" +
           "billing_impression_type\n" +
           "creative_charges\n" +
           "io_discount\n" +
           "nondiscounted_burn\n" +
           "volume_discount\n" +
           "withhold_taxes\n" +
           "is_click_to_rich\n" +
           "served_country_id\n" +
           "dcp_ad_requests\n" +
           "dcp_cpc_impressions\n" +
           "dcp_cpm_impressions\n" +
           "dcp_fraud_beacon_count\n" +
           "dcp_fraud_clicks\n" +
           "dcp_page_impressions\n" +
           "dcp_total_clicks\n" +
           "dcp_total_impressions\n" +
           "fraud_clicks\n" +
           "accidental_clicks\n" +
           "page_impressions\n" +
           "page_requests\n" +
           "pub_account_status\n" +
           "pub_account_guid\n" +
           "pub_business_segment\n" +
           "pub_origin_country_id\n" +
           "request_adpool\n" +
           "request_mkcpcadserved\n" +
           "request_handset_user_agent\n" +
           "request_uid_params\n" +
           "total_burn\n" +
           "request_adtype\n" +
           "request_apbssid\n" +
           "request_app_id\n" +
           "request_auction_conversion_factor\n" +
           "request_cat_distance\n" +
           "request_category_distance_bucket\n" +
           "request_conv_factor\n" +
           "request_creative_inc_id\n" +
           "request_csid\n" +
           "request_custom_region_fence\n" +
           "request_discarded_u_id_params\n" +
           "request_display_marketing_name\n" +
           "request_ecpm_goalseek\n" +
           "request_fill_dst\n" +
           "request_geo_category\n" +
           "request_geo_city\n" +
           "request_geo_fence\n" +
           "request_geo_type\n" +
           "request_intg_family\n" +
           "request_intg_method\n" +
           "request_intg_origin\n" +
           "request_intg_version\n" +
           "request_learning_auction_type\n" +
           "request_slot_id\n" +
           "request_mucons\n" +
           "request_muest\n" +
           "request_muh\n" +
           "request_mul\n" +
           "request_placement_id\n" +
           "predicted_clicks\n" +
           "request_predicted_engagement_map\n" +
           "request_predicted_expand_rate\n" +
           "request_req_dst\n" +
           "served_ad_format\n" +
           "request_served_dst\n" +
           "request_serving_floor\n" +
           "request_slot_served\n" +
           "request_tier_id\n" +
           "site_guid\n" +
           "terminated_clicks\n" +
           "budget_tier\n" +
           "unbilled_cpc_clicks\n" +
           "unbilled_cpm_impressions\n" +
           "user_signal_ pub_revenue\n" +
           "user_signal_clicks\n" +
           "user_valid_ad_requests\n" +
           "user_valid_page_requests\n" +
           "valid_ad_requests\n" +
           "valid_page_requests\n" +
           "is_smart_phone_device\n" +
           "handset_device_id\n" +
           "country_carrier_id";
    static String yodaBigList = "is_expandable\n" +
            "is_interstitial\n" +
            "accept_rich_media_on_web\n" +
            "ad_category\n" +
            "ad_ctr\n" +
            "adgroup_selected_bid\n" +
            "adgroup_site_preference\n" +
            "adgroup_status\n" +
            "served_ad_impresisons\n" +
            "ad_id\n" +
            "total_ad_request\n" +
            "ad_response_format\n" +
            "adgroup_category_filters\n" +
            "adgroup_daily_budget\n" +
            "adgroup_daily_spend\n" +
            "adgroup_final_landing_page\n" +
            "adgroup_gpm_id\n" +
            "adgroup_gpm_market_id\n" +
            "adgroup_gpm_name\n" +
            "adgroup_gpm_url\n" +
            "adgroup_guid\n" +
            "adgroup_inc_id\n" +
            "adgroup_is_deeply_linked\n" +
            "adgroup_is_retargeting\n" +
            "adgroup_landing_url\n" +
            "adgroup_name\n" +
            "adgroup_objective\n" +
            "adgroup_site_category\n" +
            "adgroup_sub_objective\n" +
            "adgroup_taxonomy\n" +
            "ads_render_rate\n" +
            "ads_rendered\n" +
            "adv_acc_name\n" +
            "adv_acc_status\n" +
            "adv_actual_balance\n" +
            "adv_allocated_amount\n" +
            "adv_balance_for_allocation\n" +
            "adv_created_on\n" +
            "adv_email_id\n" +
            "adv_account_guid\n" +
            "adv_manage_type\n" +
            "adv_origin_country\n" +
            "adv_promocode\n" +
            "adv_region_of_origin\n" +
            "adv_total_burn\n" +
            "adv_total_inflow\n" +
            "adv_business_segment\n" +
            "age\n" +
            "agency_revenue\n" +
            "allow_self_serve\n" +
            "app_feedback_disabled\n" +
            "app_ret_ad_impressions\n" +
            "app_ret_ad_requests\n" +
            "app_ret_app_id\n" +
            "app_ret_app_name\n" +
            "app_ret_app_url\n" +
            "app_ret_page_impressions\n" +
            "app_ret_page_request\n" +
            "app_ret_unique_count\n" +
            "app_ret_unique_count_internal\n" +
            "async_method\n" +
            "async_type\n" +
            "authorizing_platforms\n" +
            "auto_computed_lambda\n" +
            "bc_click_no_pings\n" +
            "bc_fraud_pings\n" +
            "bc_terminated_pings\n" +
            "bc_total_pings\n" +
            "bc_valid_pings\n" +
            "beacon_fraudset\n" +
            "beacon_time\n" +
            "cpm_billed_beacons\n" +
            "billed_createdon\n" +
            "billed_status\n" +
            "billing_impression_type\n" +
            "billing_ip\n" +
            "creative_charges\n" +
            "bl_fund_source_id\n" +
            "io_discount\n" +
            "nondiscounted_burn\n" +
            "volume_discount\n" +
            "withhold_taxes\n" +
            "browser_name\n" +
            "browser_version\n" +
            "burn_source\n" +
            "campaign_daily_budget\n" +
            "campaign_description\n" +
            "campaign_end_date\n" +
            "campaign_guid\n" +
            "campaign_name\n" +
            "campaign_objective\n" +
            "campaign_start_date\n" +
            "campaign_status\n" +
            "campaign_total_balance\n" +
            "campaign_total_budget\n" +
            "cbp_segment_id\n" +
            "child_io\n" +
            "ci_ret_ad_impressions\n" +
            "ci_ret_ad_request\n" +
            "ci_ret_adgroup_id\n" +
            "ci_ret_event_type\n" +
            "ci_ret_page_impressions\n" +
            "ci_ret_page_request\n" +
            "ci_ret_unique_count\n" +
            "ci_ret_unique_count_internal\n" +
            "cl_rq_ua\n" +
            "clicks\n" +
            "click_ccid\n" +
            "click_ccode\n" +
            "click_country\n" +
            "click_fraud\n" +
            "click_fraudset\n" +
            "click_handsetid\n" +
            "click_jc\n" +
            "click_other_invalidset\n" +
            "click_request_device_id\n" +
            "click_terminated\n" +
            "click_time\n" +
            "click_to_action\n" +
            "is_click_to_rich\n" +
            "click_udid_type\n" +
            "click_uid\n" +
            "click_version\n" +
            "click_x_real_ip\n" +
            "country\n" +
            "served_country_id\n" +
            "county_ccode\n" +
            "cp_user_frequency\n" +
            "cp_user_unique_count_internal\n" +
            "cpc\n" +
            "cpc_floor\n" +
            "cpc_new\n" +
            "cpm\n" +
            "cpm_floor\n" +
            "cpm_new\n" +
            "creative_content_classification\n" +
            "creative_content_provider_type\n" +
            "creative_demand_capabilities\n" +
            "creative_demand_capability_ids\n" +
            "creative_dimensions\n" +
            "creative_format\n" +
            "creative_height\n" +
            "creative_id\n" +
            "creative_landing_url\n" +
            "creative_name\n" +
            "creative_status\n" +
            "creative_text\n" +
            "creative_width\n" +
            "cta_id\n" +
            "ctr_new\n" +
            "custom_ad_unit_id\n" +
            "custom_ad_unit_name\n" +
            "custom_region_name\n" +
            "custom_segment_id\n" +
            "data_enrichment_cost\n" +
            "data_provider\n" +
            "data_seller\n" +
            "dcp_ad_requests\n" +
            "dcp_agency_revenue\n" +
            "dcp_cpc_beacon_count\n" +
            "dcp_cpc_impressions\n" +
            "dcp_cpm_beacon_count\n" +
            "dcp_cpm_impressions\n" +
            "dcp_enabled\n" +
            "dcp_fraud_beacon_count\n" +
            "dcp_fraud_clicks\n" +
            "dcp_page_impressions\n" +
            "dcp_pub_revenue\n" +
            "dcp_revenue\n" +
            "dcp_total_beacon_count\n" +
            "dcp_total_clicks\n" +
            "dcp_total_impressions\n" +
            "demand_capabilities\n" +
            "demand_capabilities_ids\n" +
            "demog_enabled\n" +
            "device_localization\n" +
            "device_networktype\n" +
            "device_orientation\n" +
            "device_type\n" +
            "device_type_id\n" +
            "diff_adv_second_adid\n" +
            "diff_adv_second_advid\n" +
            "diff_adv_second_ranks\n" +
            "dl_impid\n" +
            "down_carrier_city_id\n" +
            "down_carrier_region_id\n" +
            "download_app_id\n" +
            "download_count\n" +
            "download_duplicate_count\n" +
            "download_geo_city\n" +
            "download_geo_region\n" +
            "download_goal\n" +
            "download_hash_type\n" +
            "download_joined_count\n" +
            "download_source\n" +
            "download_time\n" +
            "download_u_id\n" +
            "download_udid_type\n" +
            "download_unjoined_count\n" +
            "ecpm\n" +
            "ecpm_new\n" +
            "effective_slot_height\n" +
            "effective_slot_size\n" +
            "effective_slot_width\n" +
            "fill_adpool\n" +
            "fraud_clicks\n" +
            "freq_cap_ducation\n" +
            "frequency_cap\n" +
            "gender\n" +
            "geo_city\n" +
            "geo_region\n" +
            "geo_targeting_constituent\n" +
            "handset_density\n" +
            "handset_external_id\n" +
            "handset_height\n" +
            "handset_manufacturer\n" +
            "handset_model\n" +
            "handset_width\n" +
            "impression_id\n" +
            "impression_poi_map\n" +
            "inmobi_revenue\n" +
            "install_count\n" +
            "integration_direct\n" +
            "integration_family\n" +
            "integration_method\n" +
            "integration_origin\n" +
            "integration_source_name\n" +
            "integration_source_type\n" +
            "integration_version\n" +
            "interstitial_orientation\n" +
            "io_end_date\n" +
            "io_net_value\n" +
            "io_start_date\n" +
            "io_status\n" +
            "is_active\n" +
            "is_arc_enabled\n" +
            "is_banner_creative\n" +
            "is_cbp_ad_group\n" +
            "is_cpm_only\n" +
            "is_frequency_cap_enabled\n" +
            "is_geo_enabled\n" +
            "is_geo_targeted\n" +
            "is_impression_geo_targeted\n" +
            "is_predicted_cvr_null\n" +
            "is_rewarded_slot\n" +
            "is_smart_phone_device\n" +
            "is_smart_phone_old\n" +
            "is_super_tier\n" +
            "is_tablet\n" +
            "joined_click_hash_type\n" +
            "lambda_used\n" +
            "learning_phase\n" +
            "location_category\n" +
            "location_source\n" +
            "log_type\n" +
            "master_advertiser\n" +
            "master_advertiser_id\n" +
            "miscellaneous_site_category\n" +
            "native_content_layout\n" +
            "network_type\n" +
            "nfr\n" +
            "nfr_new\n" +
            "nofund_burn\n" +
            "normal_burn\n" +
            "normalized_user_id\n" +
            "num_candidate_adgroups\n" +
            "num_candidate_ads\n" +
            "num_candidate_advs\n" +
            "operating_system\n" +
            "operating_system_id\n" +
            "operating_system_version\n" +
            "operator\n" +
            "accidental_clicks\n" +
            "overall_ctr\n" +
            "overall_ecpm\n" +
            "overall_impressions\n" +
            "overall_nfr\n" +
            "page_ctr\n" +
            "page_impressions\n" +
            "page_requests\n" +
            "parent_io\n" +
            "platform\n" +
            "predicted_ecpm\n" +
            "price_markup\n" +
            "pricing_model_id\n" +
            "pricing_model_type\n" +
            "primary_goal\n" +
            "pub_account_status\n" +
            "pub_created_on\n" +
            "pub_email_id\n" +
            "pub_account_guid\n" +
            "pub_manage_type\n" +
            "pub_name\n" +
            "pub_origin_country\n" +
            "pub_promocode\n" +
            "pub_region_of_origin\n" +
            "pub_revenue\n" +
            "pub_business_segment\n" +
            "pub_origin_country_id\n" +
            "publisher_platform\n" +
            "region\n" +
            "request_adpool\n" +
            "request_mkcpcadserved\n" +
            "request_ad_format\n" +
            "request_ad_formatter\n" +
            "request_ad_frequency\n" +
            "request_ad_logic\n" +
            "request_ad_recency\n" +
            "request_adgroup_frequency\n" +
            "request_adgroup_recency\n" +
            "request_all_uid_type\n" +
            "country_carrier_id\n" +
            "request_code_version\n" +
            "request_derived_latlon\n" +
            "request_handset_user_agent\n" +
            "handset_device_id\n" +
            "request_host\n" +
            "request_ip\n" +
            "request_is_geo_enabled\n" +
            "request_market\n" +
            "request_nfr\n" +
            "request_nodeinfo\n" +
            "request_orig_handset\n" +
            "request_page_url\n" +
            "request_poi_map\n" +
            "request_ref_tag\n" +
            "request_selected_uid_type\n" +
            "request_system_latlon\n" +
            "request_time\n" +
            "request_uid_params\n" +
            "request_uid\n" +
            "request_uparams\n" +
            "request_version\n" +
            "request_x_header\n" +
            "request_x_user_agent\n" +
            "requested_ad_type\n" +
            "requested_city\n" +
            "requested_geo_city\n" +
            "requested_geo_city_id\n" +
            "requested_geo_state\n" +
            "requested_geo_state_id\n" +
            "requested_geo_zipcode\n" +
            "requested_slot\n" +
            "requested_state\n" +
            "requested_zip\n" +
            "total_burn\n" +
            "rich_text_ad_slot\n" +
            "risky_burn\n" +
            "rm_avg_time_dwell\n" +
            "rm_cta_count\n" +
            "rm_demand\n" +
            "rm_dismiss_count\n" +
            "rm_dlf_count\n" +
            "rm_dls_count\n" +
            "rm_dwell_time\n" +
            "rm_expand_count\n" +
            "rm_media_auto_play_count\n" +
            "rm_media_end_count\n" +
            "rm_media_play_count\n" +
            "rm_media_q1_count\n" +
            "rm_media_q2_count\n" +
            "rm_media_q3_count\n" +
            "rm_media_start_count\n" +
            "rm_source\n" +
            "rm_sprout_id\n" +
            "rm_supply\n" +
            "rm_total\n" +
            "rm_views\n" +
            "request_adtype\n" +
            "request_apbssid\n" +
            "request_app_id\n" +
            "request_auction_conversion_factor\n" +
            "request_cat_distance\n" +
            "request_category_distance_bucket\n" +
            "request_conv_factor\n" +
            "request_creative_inc_id\n" +
            "request_csid\n" +
            "request_custom_region_fence\n" +
            "request_discarded_u_id_params\n" +
            "request_display_marketing_name\n" +
            "request_ecpm_goalseek\n" +
            "request_fill_dst\n" +
            "request_geo_category\n" +
            "request_geo_city\n" +
            "request_geo_fence\n" +
            "request_geo_type\n" +
            "request_intg_family\n" +
            "request_intg_method\n" +
            "request_intg_origin\n" +
            "request_intg_version\n" +
            "request_learning_auction_type\n" +
            "request_slot_id\n" +
            "request_mucons\n" +
            "request_muest\n" +
            "request_muh\n" +
            "request_mul\n" +
            "request_placement_id\n" +
            "predicted_clicks\n" +
            "request_predicted_engagement_map\n" +
            "request_predicted_expand_rate\n" +
            "request_req_dst\n" +
            "served_ad_format\n" +
            "request_served_dst\n" +
            "request_serving_floor\n" +
            "request_slot_served\n" +
            "request_tier_id\n" +
            "salesforce_id\n" +
            "same_adv_second_adid\n" +
            "same_adv_second_advid\n" +
            "same_adv_second_ranks\n" +
            "segment_country\n" +
            "segment_dcp_enabled\n" +
            "segment_device\n" +
            "segment_ecpm_goal\n" +
            "segment_ecpm_goal_enable\n" +
            "segment_id\n" +
            "segment_name\n" +
            "segment_network\n" +
            "segment_os\n" +
            "segment_retargeting_unique_count_internal\n" +
            "segment_site_id\n" +
            "served_city\n" +
            "served_custom_region\n" +
            "served_fence\n" +
            "served_slot\n" +
            "served_state\n" +
            "served_zipcode\n" +
            "site_ad_category\n" +
            "site_ad_group_preference\n" +
            "site_blocked\n" +
            "site_bolt_enabled\n" +
            "site_channel\n" +
            "site_content_classification\n" +
            "site_cpc_floor\n" +
            "site_cpm_floor\n" +
            "site_created_on\n" +
            "site_demand_capability\n" +
            "site_ecpm_goal\n" +
            "site_ecpm_goal_enable\n" +
            "site_floor_price\n" +
            "site_guid\n" +
            "site_inc_id\n" +
            "site_is_cpm_only\n" +
            "site_name\n" +
            "site_rev_share\n" +
            "site_status\n" +
            "site_url\n" +
            "supply_side_custom_region\n" +
            "target_cpa\n" +
            "targeting_site_category\n" +
            "template_capabilities\n" +
            "template_id\n" +
            "template_name\n" +
            "template_supply_type\n" +
            "template_type\n" +
            "terminated_clicks\n" +
            "text_banner_preference\n" +
            "budget_tier\n" +
            "total_ad_imp\n" +
            "tracking_partner_name\n" +
            "tracking_partner_url_details\n" +
            "tracking_supported\n" +
            "unbilled_cpc_clicks\n" +
            "unbilled_cpm_impressions\n" +
            "unique_user_count\n" +
            "user_ad_impressions\n" +
            "user_app_dist_unique_count\n" +
            "user_app_dist_unique_count_internal\n" +
            "user_category\n" +
            "user_demog_age\n" +
            "user_demog_age_score\n" +
            "user_demog_education\n" +
            "user_demog_education_score\n" +
            "user_demog_ethnicity\n" +
            "user_demog_ethnicity_score\n" +
            "user_demog_gender\n" +
            "user_demog_gender_score\n" +
            "user_demog_haschildren\n" +
            "user_demog_haschildren_score\n" +
            "user_demog_hhi\n" +
            "user_demog_hhi_score\n" +
            "user_demog_language\n" +
            "user_demog_language_score\n" +
            "user_factual_unique_count\n" +
            "user_factual_unique_count_internal\n" +
            "user_factual_valid_ad_requests\n" +
            "user_lambda\n" +
            "user_life_span\n" +
            "user_life_unique_count\n" +
            "user_life_unique_count_internal\n" +
            "user_location_context\n" +
            "user_location_context_ad_req\n" +
            "user_location_context_page_req\n" +
            "user_location_context_unique_count\n" +
            "user_location_context_unique_count_internal\n" +
            "user_ltv_account_id\n" +
            "user_ltv_app_id\n" +
            "user_ltv_data_source\n" +
            "user_ltv_segment_name\n" +
            "user_optout\n" +
            "user_page_impressions\n" +
            "user_segment_account_name\n" +
            "user_segment_app_name\n" +
            "user_segment_unique_count\n" +
            "user_segment_valid_ad_requests\n" +
            "user_sig_unique_count\n" +
            "user_sig_unique_count_internal\n" +
            "user_signal_ agency_revenue\n" +
            "user_signal_ download\n" +
            "user_signal_ pub_revenue\n" +
            "user_signal_ad_impressions\n" +
            "user_signal_clicks\n" +
            "user_signal_revenue\n" +
            "user_site_visited_count\n" +
            "user_unique_count_internal\n" +
            "user_valid_ad_requests\n" +
            "user_valid_page_requests\n" +
            "valid_ad_requests\n" +
            "valid_clicks\n" +
            "valid_page_requests\n" +
            "video_ads_settings\n" +
            "video_prebuffer_settings";

    public static void main(String[] args) {
        String ibarr[] = ib.split("\n");
        HashSet<String> ibset = new HashSet<String>();
        for(String temp:ibarr){
            ibset.add(temp);
        }

        HashSet<String> yodaset = new HashSet<String>();
        String yodaarr[] = yodaBigList.split("\n");
        for(String temp:yodaarr){
            yodaset.add(temp);
        }

        System.out.println(yodaset.size());

        System.out.println(ibset.size());

        for(String temp:yodaset){
            ibset.remove(temp);
        }



        System.out.println(ibset.size());

        for(String temp:ibset){
            System.out.println(temp);
        }
    }
}
